"""added access token

Revision ID: 543133acd074
Revises: dc6bacb29779
Create Date: 2024-08-06 00:42:44.036529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543133acd074'
down_revision: Union[str, None] = 'dc6bacb29779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_token',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_token_id'), 'access_token', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_token_id'), table_name='access_token')
    op.drop_table('access_token')
    # ### end Alembic commands ###
