"""add blacklisted column on access token model

Revision ID: b767914f15f3
Revises: 48ce88eeae3c
Create Date: 2024-08-06 22:08:30.664526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b767914f15f3'
down_revision: Union[str, None] = '48ce88eeae3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_token', sa.Column('blacklisted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_token', 'blacklisted')
    # ### end Alembic commands ###
